// @ts-nocheck
'use client';
import React, { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import dynamic from 'next/dynamic';
import { useSupabase } from '@/lib/supabase-browser';
import { fmtRupiah } from '@/lib/utils';
import { useDateRange } from '@/lib/DateRangeContext';
import { getCached, setCache } from '@/lib/dashboard-cache';

// Lazy-load emoji picker to avoid SSR issues
const EmojiPicker = dynamic(() => import('emoji-picker-react'), { ssr: false });

// Regex to detect emoji characters
const EMOJI_RE = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{FE00}-\u{FE0F}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{200D}\u{20E3}\u{E0020}-\u{E007F}]/u;

// Detect CTWA auto-generated templates (UUID-style hex names from Meta Ads)
const AUTO_GENERATED_RE = /^[0-9a-f]{8}_[0-9a-f]{4}_[0-9a-f]{4}_[0-9a-f]{4}_[0-9a-f]{12}$/;
function isAutoGenerated(name: string): boolean {
  return AUTO_GENERATED_RE.test(name);
}

// ── Template types ──
interface Template {
  id: string;
  waba_id: string;
  name: string;
  status: string;
  category: string;
  language: string;
  components: any[];
  tags?: string[];
}

interface ActiveWabaAccount {
  waba_id: string;
  waba_name: string;
}

// ── Status badge colors ──
const STATUS_STYLE: Record<string, { bg: string; color: string }> = {
  APPROVED: { bg: 'var(--badge-green-bg)', color: 'var(--green)' },
  PENDING:  { bg: 'var(--badge-yellow-bg)', color: 'var(--yellow)' },
  REJECTED: { bg: 'var(--badge-red-bg)', color: 'var(--red)' },
  PAUSED:   { bg: 'var(--bg-deep)', color: 'var(--text-secondary)' },
};

const CATEGORY_STYLE: Record<string, { bg: string; color: string }> = {
  MARKETING:      { bg: '#1e3a5f', color: '#60a5fa' },
  UTILITY:        { bg: '#1a3636', color: '#2dd4bf' },
  AUTHENTICATION: { bg: '#3b1f4a', color: '#c084fc' },
};

// ── Template Preview Component (WhatsApp chat bubble) ──
function TemplatePreview({ template, renderWaFormatted, analytics }: { template: Template; renderWaFormatted: (text: string) => React.ReactNode; analytics?: { sent: number; delivered: number; read: number; clicked: number; replied: number; cost: number } }) {
  const header = template.components?.find((c: any) => c.type === 'HEADER');
  const body = template.components?.find((c: any) => c.type === 'BODY');
  const footer = template.components?.find((c: any) => c.type === 'FOOTER');
  const buttons = template.components?.find((c: any) => c.type === 'BUTTONS');

  return (
    <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start' }}>
      {/* WhatsApp chat bubble preview */}
      <div style={{ width: 300, flexShrink: 0 }}>
        <div style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', fontWeight: 600, marginBottom: 6 }}>WhatsApp Preview</div>
        <div style={{ background: '#e5ddd5', borderRadius: 12, padding: 16, position: 'relative' }}>
          <div style={{ position: 'absolute', inset: 0, borderRadius: 12, opacity: 0.05, background: 'url("data:image/svg+xml,%3Csvg width=\'40\' height=\'40\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M20 0L0 20h10L20 10l10 10h10z\' fill=\'%23000\'/%3E%3C/svg%3E")' }} />
          <div style={{ position: 'relative', background: '#fff', borderRadius: '0 8px 8px 8px', padding: '8px 10px', maxWidth: '100%', boxShadow: '0 1px 2px rgba(0,0,0,0.13)' }}>
            {/* Header */}
            {header?.text && (
              <div style={{ fontSize: 14, fontWeight: 700, color: '#1a1a1a', marginBottom: 4, lineHeight: 1.3 }}>
                {header.text}
              </div>
            )}
            {header?.format === 'IMAGE' && (
              <div style={{ background: '#f0f0f0', borderRadius: 6, height: 120, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 6, color: '#999', fontSize: 11 }}>
                📷 Image Header
              </div>
            )}
            {/* Body */}
            <div style={{ fontSize: 13, color: '#303030', lineHeight: 1.45, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
              {body?.text ? renderWaFormatted(body.text) : <span style={{ color: '#999' }}>No body text</span>}
            </div>
            {/* Footer */}
            {footer?.text && (
              <div style={{ fontSize: 11, color: '#8c8c8c', marginTop: 6 }}>{footer.text}</div>
            )}
            {/* Timestamp */}
            <div style={{ textAlign: 'right', marginTop: 2 }}>
              <span style={{ fontSize: 10, color: '#8c8c8c' }}>12:00</span>
            </div>
          </div>
          {/* Buttons */}
          {buttons?.buttons?.length > 0 && (
            <div style={{ position: 'relative', marginTop: 4, display: 'flex', flexDirection: 'column', gap: 2 }}>
              {buttons.buttons.map((btn: any, i: number) => (
                <div key={i} style={{ background: '#fff', borderRadius: 6, padding: '7px 10px', textAlign: 'center', fontSize: 13, color: '#00a5f4', fontWeight: 500, boxShadow: '0 1px 2px rgba(0,0,0,0.08)' }}>
                  {btn.type === 'URL' ? '🔗 ' : btn.type === 'PHONE_NUMBER' ? '📞 ' : ''}{btn.text}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
      {/* Template details */}
      <div style={{ flex: 1, fontSize: 12, color: 'var(--text-secondary)' }}>
        <div style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', fontWeight: 600, marginBottom: 6 }}>Template Details</div>
        <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '4px 12px' }}>
          <span style={{ color: 'var(--text-muted)' }}>ID:</span>
          <span style={{ fontFamily: 'monospace', fontSize: 11 }}>{template.id}</span>
          <span style={{ color: 'var(--text-muted)' }}>Category:</span>
          <span>{template.category}</span>
          <span style={{ color: 'var(--text-muted)' }}>Language:</span>
          <span>{template.language}</span>
          <span style={{ color: 'var(--text-muted)' }}>Status:</span>
          <span>{template.status}</span>
          {header && (
            <>
              <span style={{ color: 'var(--text-muted)' }}>Header:</span>
              <span>{header.format || 'TEXT'}{header.text ? `: ${header.text}` : ''}</span>
            </>
          )}
          {buttons?.buttons?.length > 0 && (
            <>
              <span style={{ color: 'var(--text-muted)' }}>Buttons:</span>
              <span>{buttons.buttons.map((b: any) => b.text).join(', ')}</span>
            </>
          )}
        </div>

        {/* Performance section */}
        {analytics && analytics.sent > 0 && (
          <div style={{ marginTop: 16 }}>
            <div style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', fontWeight: 600, marginBottom: 6 }}>Performance (90d)</div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 }}>
              {[
                { label: 'Sent', value: analytics.sent.toLocaleString() },
                { label: 'Delivered', value: analytics.delivered.toLocaleString() },
                { label: 'Read', value: analytics.read.toLocaleString() },
              ].map(m => (
                <div key={m.label} style={{ background: 'var(--bg)', borderRadius: 6, padding: '8px 10px', textAlign: 'center' }}>
                  <div style={{ fontSize: 9, color: 'var(--text-muted)', textTransform: 'uppercase' }}>{m.label}</div>
                  <div style={{ fontSize: 14, fontWeight: 700, fontFamily: 'monospace', color: 'var(--text)' }}>{m.value}</div>
                </div>
              ))}
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginTop: 8 }}>
              <div style={{ background: 'var(--bg)', borderRadius: 6, padding: '8px 10px', textAlign: 'center' }}>
                <div style={{ fontSize: 9, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Click Rate</div>
                <div style={{ fontSize: 14, fontWeight: 700, fontFamily: 'monospace', color: '#60a5fa' }}>
                  {analytics.read > 0 ? (analytics.clicked / analytics.read * 100).toFixed(1) + '%' : '—'}
                </div>
              </div>
              <div style={{ background: 'var(--bg)', borderRadius: 6, padding: '8px 10px', textAlign: 'center' }}>
                <div style={{ fontSize: 9, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Reply Rate</div>
                <div style={{ fontSize: 14, fontWeight: 700, fontFamily: 'monospace', color: 'var(--green)' }}>
                  {analytics.read > 0 ? (analytics.replied / analytics.read * 100).toFixed(1) + '%' : '—'}
                </div>
              </div>
              <div style={{ background: 'var(--bg)', borderRadius: 6, padding: '8px 10px', textAlign: 'center' }}>
                <div style={{ fontSize: 9, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Cost/Reply</div>
                <div style={{ fontSize: 14, fontWeight: 700, fontFamily: 'monospace', color: 'var(--yellow)' }}>
                  {analytics.replied > 0 && analytics.cost > 0 ? 'Rp ' + Math.round(analytics.cost / analytics.replied).toLocaleString() : '—'}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default function WabaManagementPage() {
  const supabase = useSupabase();
  const { dateRange, loading: dateLoading } = useDateRange();

  // ── Template state ──
  const [templates, setTemplates] = useState<Template[]>([]);
  const [activeWabaAccounts, setActiveWabaAccounts] = useState<ActiveWabaAccount[]>([]);
  const [selectedCreateWabaId, setSelectedCreateWabaId] = useState('');
  const [loadingTemplates, setLoadingTemplates] = useState(true);
  const [loadingAccounts, setLoadingAccounts] = useState(true);
  const [templateError, setTemplateError] = useState<string | null>(null);
  const [templateAnalyticsError, setTemplateAnalyticsError] = useState<string | null>(null);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [creating, setCreating] = useState(false);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [showAutoGenerated, setShowAutoGenerated] = useState(false);
  const [showOnlySent, setShowOnlySent] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterTag, setFilterTag] = useState<string | null>(null);
  const [editingTagId, setEditingTagId] = useState<string | null>(null);
  const [tagInput, setTagInput] = useState('');
  const [expandedTemplate, setExpandedTemplate] = useState<string | null>(null);
  const [templateAnalytics, setTemplateAnalytics] = useState<Record<string, { sent: number; delivered: number; read: number; clicked: number; replied: number; cost: number }>>({});
  const [templateAnalyticsDaily, setTemplateAnalyticsDaily] = useState<{ date: string; sent: number; delivered: number; read: number; clicked: number; replied: number }[]>([]);
  const [loadingTplAnalytics, setLoadingTplAnalytics] = useState(false);
  const [copiedName, setCopiedName] = useState<string | null>(null);
  const [syncing, setSyncing] = useState(false);
  const [lastSynced, setLastSynced] = useState<string | null>(null);
  const [syncNotice, setSyncNotice] = useState<{ tone: 'success' | 'warning' | 'error'; text: string } | null>(null);
  const [userRole, setUserRole] = useState<string | null>(null);

  // ── Create form state ──
  const [formName, setFormName] = useState('');
  const [formCategory, setFormCategory] = useState<'MARKETING' | 'UTILITY' | 'AUTHENTICATION'>('MARKETING');
  const [formLanguage, setFormLanguage] = useState('id');
  const [formBody, setFormBody] = useState('');
  const [formHeader, setFormHeader] = useState('');
  const [formFooter, setFormFooter] = useState('');
  const [formButtons, setFormButtons] = useState<string[]>([]);
  const [formError, setFormError] = useState<string | null>(null);
  const [varSamples, setVarSamples] = useState<Record<string, string>>({});
  const bodyRef = useRef<HTMLTextAreaElement>(null);
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const emojiPickerRef = useRef<HTMLDivElement>(null);

  // ── Click-outside to close emoji picker ──
  useEffect(() => {
    if (!showEmojiPicker) return;
    function handleClick(e: MouseEvent) {
      if (emojiPickerRef.current && !emojiPickerRef.current.contains(e.target as Node)) {
        setShowEmojiPicker(false);
      }
    }
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [showEmojiPicker]);

  // ── Insert emoji at cursor ──
  function insertEmoji(emojiData: any) {
    const emoji = emojiData.emoji;
    const el = bodyRef.current;
    const pos = el ? el.selectionStart : formBody.length;
    const newText = formBody.substring(0, pos) + emoji + formBody.substring(pos);
    setFormBody(newText);
    setShowEmojiPicker(false);
    setTimeout(() => { if (el) { el.focus(); const np = pos + emoji.length; el.setSelectionRange(np, np); } }, 0);
  }

  // ── Body formatting helpers ──
  function wrapSelection(prefix: string, suffix: string) {
    const el = bodyRef.current;
    if (!el) return;
    const start = el.selectionStart;
    const end = el.selectionEnd;
    const selected = formBody.substring(start, end);
    const before = formBody.substring(0, start);
    const after = formBody.substring(end);
    if (selected) {
      const newText = before + prefix + selected + suffix + after;
      setFormBody(newText);
      setTimeout(() => { el.focus(); el.setSelectionRange(start + prefix.length, end + prefix.length); }, 0);
    } else {
      const newText = before + prefix + suffix + after;
      setFormBody(newText);
      setTimeout(() => { el.focus(); el.setSelectionRange(start + prefix.length, start + prefix.length); }, 0);
    }
  }

  function addVariable() {
    const nextNum = (detectedVars.length > 0)
      ? Math.max(...detectedVars.map(v => parseInt(v.replace(/\D/g, '')))) + 1
      : 1;
    const el = bodyRef.current;
    const pos = el ? el.selectionStart : formBody.length;
    const newText = formBody.substring(0, pos) + `{{${nextNum}}}` + formBody.substring(pos);
    setFormBody(newText);
    setTimeout(() => { if (el) { el.focus(); const np = pos + `{{${nextNum}}}`.length; el.setSelectionRange(np, np); } }, 0);
  }

  // ── Auto-detect variables in body text ──
  const detectedVars = useMemo(() => {
    const matches = formBody.match(/\{\{(\d+)\}\}/g) || [];
    const unique = [...new Set(matches)].sort((a, b) => {
      const numA = parseInt(a.replace(/\D/g, ''));
      const numB = parseInt(b.replace(/\D/g, ''));
      return numA - numB;
    });
    return unique;
  }, [formBody]);

  // ── Per-field real-time validation ──
  const nameErrors = useMemo(() => {
    const errs: string[] = [];
    if (!formName) return errs;
    const sanitized = formName.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
    if (!/^[a-z][a-z0-9_]*$/.test(sanitized)) {
      errs.push('Must start with a letter and contain only lowercase letters, numbers, and underscores.');
    }
    if (formName.length > 512) errs.push(`Too long (${formName.length}/512 characters).`);
    return errs;
  }, [formName]);

  const headerErrors = useMemo(() => {
    const errs: string[] = [];
    if (!formHeader) return errs;
    if (formHeader.length > 60) errs.push(`Exceeds maximum length (${formHeader.length}/60 characters).`);
    const headerVars = formHeader.match(/\{\{(\d+)\}\}/g) || [];
    if (headerVars.length > 1) errs.push('Header supports only 1 variable maximum.');
    if (EMOJI_RE.test(formHeader)) errs.push('Emoji not allowed in header text.');
    if (/\n/.test(formHeader)) errs.push('Newlines not allowed in header.');
    if (/[*_~`]/.test(formHeader)) errs.push('Formatting markup (*bold*, _italic_, etc.) not allowed in header.');
    return errs;
  }, [formHeader]);

  const bodyErrors = useMemo(() => {
    const errs: string[] = [];
    if (!formBody) return errs;
    if (formBody.length > 1024) errs.push(`Exceeds maximum length (${formBody.length}/1024 characters).`);
    if (/\t/.test(formBody)) errs.push('Tab characters are not allowed.');
    if (/ {5,}/.test(formBody)) errs.push('No more than 4 consecutive spaces allowed.');
    if (/\n{3,}/.test(formBody)) errs.push('No more than 2 consecutive newlines allowed.');
    if (detectedVars.length > 100) errs.push(`Too many variables (${detectedVars.length}/100 maximum).`);
    if (formBody.trim() && detectedVars.length > 0) {
      const textWithoutVars = formBody.replace(/\{\{\d+\}\}/g, '').trim();
      const wordCount = textWithoutVars.split(/\s+/).filter(w => w.length > 0).length;
      const minWords = 2 * detectedVars.length + 1;
      if (wordCount < minWords) {
        errs.push(`Too many variables for message length. Need at least ${minWords} words for ${detectedVars.length} variable(s), currently have ${wordCount}.`);
      }
      if (/\{\{\d+\}\}\s*\{\{\d+\}\}/.test(formBody)) errs.push('Variables cannot be adjacent — add text between them.');
      if (/^\s*\{\{\d+\}\}/.test(formBody)) errs.push('Body cannot start with a variable.');
      if (/\{\{\d+\}\}\s*[.!?,;:]*\s*$/.test(formBody)) errs.push('Body cannot end with a variable.');
      const varNums = detectedVars.map(v => parseInt(v.replace(/\D/g, ''))).sort((a, b) => a - b);
      for (let i = 0; i < varNums.length; i++) {
        if (varNums[i] !== i + 1) { errs.push(`Variable numbering must be sequential (gap at {{${varNums[i]}}}).`); break; }
      }
    }
    return errs;
  }, [formBody, detectedVars]);

  const footerErrors = useMemo(() => {
    const errs: string[] = [];
    if (!formFooter) return errs;
    if (formFooter.length > 60) errs.push(`Exceeds maximum length (${formFooter.length}/60 characters).`);
    if (/\{\{\d+\}\}/.test(formFooter)) errs.push('Variables not allowed in footer.');
    if (EMOJI_RE.test(formFooter)) errs.push('Emoji not allowed in footer.');
    if (/[*_~`]/.test(formFooter)) errs.push('Formatting markup not allowed in footer.');
    if (/\n/.test(formFooter)) errs.push('Newlines not allowed in footer.');
    return errs;
  }, [formFooter]);

  const buttonErrors = useMemo(() => {
    const errs: string[] = [];
    const activeButtons = formButtons.filter(b => b.trim());
    if (activeButtons.length > 10) errs.push('Maximum 10 buttons allowed.');
    formButtons.forEach((btn, i) => {
      if (btn.trim() && btn.trim().length > 25) errs.push(`Button ${i + 1} exceeds maximum length (${btn.trim().length}/25).`);
    });
    return errs;
  }, [formButtons]);

  const hasValidationErrors = nameErrors.length + headerErrors.length + bodyErrors.length + footerErrors.length + buttonErrors.length > 0;

  // ── Filter auto-generated templates ──
  const autoGeneratedCount = useMemo(() => templates.filter(t => isAutoGenerated(t.name)).length, [templates]);
  const allTags = useMemo(() => {
    const set = new Set<string>();
    templates.forEach(t => (t.tags || []).forEach(tag => set.add(tag)));
    return [...set].sort();
  }, [templates]);
  const filteredTemplates = useMemo(() => {
    let list = showAutoGenerated ? templates : templates.filter(t => !isAutoGenerated(t.name));
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      list = list.filter(t => t.name.toLowerCase().includes(q) || (t.tags || []).some(tag => tag.includes(q)));
    }
    if (filterTag) {
      list = list.filter(t => (t.tags || []).includes(filterTag));
    }
    if (showOnlySent) {
      list = list.filter(t => (templateAnalytics[t.id]?.sent || 0) > 0);
      return [...list].sort((a, b) => {
        const sentA = templateAnalytics[a.id]?.sent || 0;
        const sentB = templateAnalytics[b.id]?.sent || 0;
        if (sentA !== sentB) return sentB - sentA;
        return Number(b.id) - Number(a.id);
      });
    }
    return [...list].sort((a, b) => Number(b.id) - Number(a.id));
  }, [templates, showAutoGenerated, showOnlySent, searchQuery, filterTag, templateAnalytics]);

  const wabaNameById = useMemo(() => {
    const map: Record<string, string> = {};
    activeWabaAccounts.forEach((account) => {
      map[account.waba_id] = account.waba_name;
    });
    return map;
  }, [activeWabaAccounts]);

  const canSyncTemplates = userRole === 'owner' || userRole === 'finance';
  const hasMultipleWabaAccounts = activeWabaAccounts.length > 1;

  // ── Preview body with samples substituted ──
  const previewBody = useMemo(() => {
    if (!formBody) return '';
    let text = formBody;
    for (const v of detectedVars) {
      const key = v.replace(/[{}]/g, '');
      const sample = varSamples[key];
      if (sample) {
        text = text.replaceAll(v, sample);
      }
    }
    return text;
  }, [formBody, detectedVars, varSamples]);

  // ── Analytics state ──
  const [adsData, setAdsData] = useState([]);
  const [channelData, setChannelData] = useState([]);
  const [shipmentCounts, setShipmentCounts] = useState([]);
  const [loadingAnalytics, setLoadingAnalytics] = useState(true);

  useEffect(() => {
    let cancelled = false;

    Promise.all([
      supabase.auth.getUser(),
      supabase.from('waba_accounts').select('waba_id, waba_name').eq('is_active', true).order('waba_name'),
    ]).then(async ([userRes, accountsRes]) => {
      if (cancelled) return;

      if (accountsRes.error) {
        console.error('[WABA] active accounts error:', accountsRes.error);
      } else {
        const accounts = accountsRes.data || [];
        setActiveWabaAccounts(accounts);
        setSelectedCreateWabaId((prev) => {
          if (prev && accounts.some((account) => account.waba_id === prev)) return prev;
          return accounts[0]?.waba_id || '';
        });
      }

      const user = userRes.data.user;
      if (user) {
        const { data: profile } = await supabase
          .from('profiles')
          .select('role')
          .eq('id', user.id)
          .single();

        if (!cancelled) {
          setUserRole(profile?.role || null);
        }
      }

      if (!cancelled) {
        setLoadingAccounts(false);
      }
    }).catch((err) => {
      if (cancelled) return;
      console.error('[WABA] page bootstrap error:', err);
      setLoadingAccounts(false);
    });

    return () => {
      cancelled = true;
    };
  }, [supabase]);

  // ── Fetch templates from DB (instant, no pagination needed) ──
  const fetchTemplates = useCallback(async () => {
    setLoadingTemplates(true);
    setTemplateError(null);
    try {
      const res = await fetch('/api/waba-templates');
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to fetch templates');
      setTemplates(json.data || []);
      if (Array.isArray(json.accounts) && json.accounts.length > 0) {
        setActiveWabaAccounts(json.accounts);
        setSelectedCreateWabaId((prev) => {
          if (prev && json.accounts.some((account: ActiveWabaAccount) => account.waba_id === prev)) return prev;
          return json.accounts[0]?.waba_id || '';
        });
      }
    } catch (err: any) {
      setTemplateError(err.message);
    } finally {
      setLoadingTemplates(false);
    }
  }, []);

  useEffect(() => { fetchTemplates(); }, [fetchTemplates]);

  // ── Fetch last sync time ──
  useEffect(() => {
    supabase
      .from('waba_template_sync_log')
      .select('created_at')
      .in('status', ['success', 'partial'])
      .order('created_at', { ascending: false })
      .limit(1)
      .then(({ data }) => {
        if (data?.[0]?.created_at) setLastSynced(data[0].created_at);
      });
  }, [supabase]);

  // ── Sync templates ──
  const handleSync = useCallback(async (mode: 'cron' | 'full') => {
    if (!canSyncTemplates) return;
    setSyncing(true);
    setSyncNotice(null);
    try {
      const res = await fetch('/api/waba-template-sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Sync failed');
      setLastSynced(new Date().toISOString());
      if (json.status === 'partial') {
        const details = Array.isArray(json.errors) && json.errors.length > 0 ? ` ${json.errors.slice(0, 2).join('; ')}` : '';
        setSyncNotice({ tone: 'warning', text: `Sync selesai sebagian.${details}` });
      } else {
        setSyncNotice({
          tone: 'success',
          text: `Sync selesai: ${json.templates_synced || 0} template dan ${json.analytics_rows_upserted || 0} baris analytics.`,
        });
      }
      fetchTemplates();
    } catch (err: any) {
      setSyncNotice({ tone: 'error', text: err.message });
    } finally {
      setSyncing(false);
    }
  }, [canSyncTemplates, fetchTemplates]);

  // ── Fetch per-template analytics from DB after templates load ──
  useEffect(() => {
    if (loadingTemplates) return;
    setTemplateAnalytics({});
    setTemplateAnalyticsDaily([]);
    setTemplateAnalyticsError(null);

    if (loadingTemplates || templates.length === 0) return;
    const allIds = templates
      .filter(t => t.status === 'APPROVED')
      .map(t => t.id);
    if (allIds.length === 0) return;

    const now = new Date();
    const end = now.toISOString().split('T')[0];
    const start90 = new Date(now);
    start90.setDate(start90.getDate() - 90);
    const start = start90.toISOString().split('T')[0];

    setLoadingTplAnalytics(true);
    fetch(`/api/waba-template-analytics?template_ids=${allIds.join(',')}&start=${start}&end=${end}`)
      .then(async (res) => {
        const json = await res.json();
        if (!res.ok) throw new Error(json.error || 'Failed to fetch template analytics');
        return json;
      })
      .then(json => {
        if (json.byTemplate) setTemplateAnalytics(json.byTemplate);
        if (json.daily) setTemplateAnalyticsDaily(json.daily);
      })
      .catch(err => {
        console.error('[template-analytics] fetch error:', err);
        setTemplateAnalyticsError(err.message);
      })
      .finally(() => setLoadingTplAnalytics(false));
  }, [templates, loadingTemplates]);

  // ── Fetch analytics data ──
  useEffect(() => {
    if (!dateRange.from || !dateRange.to) return;
    const { from, to } = dateRange;

    const cachedAds = getCached('waba_ads_data', from, to);
    const cachedCh = getCached('waba_channel_data', from, to);
    const cachedSc = getCached('waba_shipment_counts', from, to);

    if (cachedAds && cachedCh && cachedSc) {
      setAdsData(cachedAds);
      setChannelData(cachedCh);
      setShipmentCounts(cachedSc);
      setLoadingAnalytics(false);
      return;
    }

    setLoadingAnalytics(true);
    Promise.all([
      supabase.from('daily_ads_spend')
        .select('date, source, spent, data_source, impressions, cpm')
        .gte('date', from).lte('date', to)
        .eq('data_source', 'whatsapp_api'),
      supabase.from('daily_channel_data')
        .select('date, product, channel, net_sales')
        .gte('date', from).lte('date', to)
        .eq('channel', 'WABA'),
      supabase.from('summary_daily_customer_type')
        .select('date, sales_channel, order_count')
        .gte('date', from).lte('date', to)
        .eq('sales_channel', 'WABA'),
    ]).then(([adsRes, chRes, scRes]) => {
      if (adsRes.error) console.error('[WABA] daily_ads_spend error:', adsRes.error);
      if (chRes.error) console.error('[WABA] daily_channel_data error:', chRes.error);
      if (scRes.error) console.error('[WABA] shipment_counts error:', scRes.error);

      const ads = adsRes.data || [];
      const ch = chRes.data || [];
      // Map summary_daily_customer_type rows to the shape expected by wabaAnalysis
      const sc = (scRes.data || []).map((d: any) => ({
        date: d.date,
        channel: d.sales_channel,
        order_count: Number(d.order_count || 0),
      }));

      setCache('waba_ads_data', from, to, ads);
      setCache('waba_channel_data', from, to, ch);
      setCache('waba_shipment_counts', from, to, sc);

      setAdsData(ads);
      setChannelData(ch);
      setShipmentCounts(sc);
      setLoadingAnalytics(false);
    });
  }, [dateRange, supabase]);

  // ── WABA Promotion Analysis ──
  const wabaAnalysis = useMemo(() => {
    const byDate: Record<string, { sent: number; delivered: number; orders: number; cost: number; revenue: number }> = {};

    adsData.forEach(d => {
      if (!byDate[d.date]) byDate[d.date] = { sent: 0, delivered: 0, orders: 0, cost: 0, revenue: 0 };
      byDate[d.date].sent += Number(d.impressions || 0);
      byDate[d.date].delivered += Number(d.cpm || 0);
      byDate[d.date].cost += Math.abs(Number(d.spent || 0));
    });

    channelData.forEach(d => {
      if (!byDate[d.date]) byDate[d.date] = { sent: 0, delivered: 0, orders: 0, cost: 0, revenue: 0 };
      byDate[d.date].revenue += Number(d.net_sales || 0);
    });

    shipmentCounts.forEach(d => {
      if (!byDate[d.date]) byDate[d.date] = { sent: 0, delivered: 0, orders: 0, cost: 0, revenue: 0 };
      byDate[d.date].orders += Number(d.order_count || 0);
    });

    const rows = Object.entries(byDate)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([date, v]) => ({
        date,
        dateLabel: `${new Date(date).getDate()}/${new Date(date).getMonth() + 1}`,
        ...v,
        deliveryRate: v.sent > 0 ? (v.delivered / v.sent) * 100 : 0,
        costPerOrder: v.orders > 0 ? v.cost / v.orders : 0,
      }));

    const totals = rows.reduce((acc, r) => ({
      sent: acc.sent + r.sent,
      delivered: acc.delivered + r.delivered,
      orders: acc.orders + r.orders,
      cost: acc.cost + r.cost,
      revenue: acc.revenue + r.revenue,
    }), { sent: 0, delivered: 0, orders: 0, cost: 0, revenue: 0 });

    return {
      rows,
      totals: {
        ...totals,
        deliveryRate: totals.sent > 0 ? (totals.delivered / totals.sent) * 100 : 0,
        costPerOrder: totals.orders > 0 ? totals.cost / totals.orders : 0,
      },
    };
  }, [adsData, channelData, shipmentCounts]);

  // ── Tag management ──
  async function handleUpdateTags(templateId: string, newTags: string[]) {
    try {
      const res = await fetch('/api/waba-templates', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: templateId, tags: newTags }),
      });
      if (!res.ok) throw new Error('Failed to update tags');
      setTemplates(prev => prev.map(t => t.id === templateId ? { ...t, tags: newTags } : t));
    } catch (err: any) {
      console.error('[tags] Update error:', err.message);
    }
  }

  // ── Create template handler ──
  async function handleCreate() {
    setFormError(null);
    if (!formBody.trim()) { setFormError('Body text is required'); return; }
    if (!formName.trim()) { setFormError('Template name is required'); return; }

    const components: any[] = [];
    if (formHeader.trim()) {
      components.push({ type: 'HEADER', format: 'TEXT', text: formHeader.trim() });
    }
    const bodyComponent: any = { type: 'BODY', text: formBody.trim() };
    // Include variable samples as example for Meta review
    if (detectedVars.length > 0) {
      const exampleValues = detectedVars.map(v => {
        const key = v.replace(/[{}]/g, '');
        return varSamples[key] || v;
      });
      bodyComponent.example = { body_text: [exampleValues] };
    }
    components.push(bodyComponent);
    if (formFooter.trim()) {
      components.push({ type: 'FOOTER', text: formFooter.trim() });
    }
    if (formButtons.filter(b => b.trim()).length > 0) {
      components.push({
        type: 'BUTTONS',
        buttons: formButtons.filter(b => b.trim()).map(text => ({ type: 'QUICK_REPLY', text: text.trim() })),
      });
    }

    setCreating(true);
    try {
      if (!selectedCreateWabaId) {
        throw new Error('Pilih WABA account tujuan terlebih dahulu.');
      }
      const res = await fetch('/api/waba-templates', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: formName, category: formCategory, language: formLanguage, components, waba_id: selectedCreateWabaId }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to create template');

      // Reset form and refetch
      setFormName(''); setFormBody(''); setFormHeader(''); setFormFooter(''); setFormButtons([]); setVarSamples({});
      setShowCreateForm(false);
      fetchTemplates();
    } catch (err: any) {
      setFormError(err.message);
    } finally {
      setCreating(false);
    }
  }

  // ── Delete template handler ──
  async function handleDelete(template: Template) {
    if (!window.confirm(`Delete template "${template.name}"? This cannot be undone.`)) return;
    setDeleting(template.id);
    try {
      const res = await fetch('/api/waba-templates', {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ hsm_id: template.id, name: template.name, waba_id: template.waba_id }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || 'Failed to delete template');
      setTemplates(prev => prev.filter(t => t.id !== template.id));
    } catch (err: any) {
      alert('Delete failed: ' + err.message);
    } finally {
      setDeleting(null);
    }
  }

  // ── Extract body text from components ──
  function getBodyText(components: any[]): string {
    const body = components?.find(c => c.type === 'BODY');
    return body?.text || '—';
  }

  // ── Render WhatsApp-formatted text as React elements ──
  function renderWaFormatted(text: string) {
    // Process formatting: *bold*, _italic_, ~strikethrough~, ```monospace```
    const parts: React.ReactNode[] = [];
    // Use regex to find formatted segments
    const regex = /(\*([^*]+)\*|_([^_]+)_|~([^~]+)~|```([^`]+)```)/g;
    let lastIndex = 0;
    let match;
    let key = 0;
    while ((match = regex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        parts.push(text.substring(lastIndex, match.index));
      }
      if (match[2]) parts.push(<strong key={key++}>{match[2]}</strong>);
      else if (match[3]) parts.push(<em key={key++}>{match[3]}</em>);
      else if (match[4]) parts.push(<s key={key++}>{match[4]}</s>);
      else if (match[5]) parts.push(<code key={key++} style={{ background: '#f0f0f0', borderRadius: 3, padding: '1px 4px', fontFamily: 'monospace', fontSize: 12 }}>{match[5]}</code>);
      lastIndex = match.index + match[0].length;
    }
    if (lastIndex < text.length) parts.push(text.substring(lastIndex));
    return parts.length > 0 ? parts : text;
  }

  // ── Styles ──
  const card = { background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12, padding: 16 };
  const thStyle = { padding: '8px 10px', color: 'var(--dim)', fontWeight: 600, fontSize: 10, textTransform: 'uppercase' as const };
  const tdStyle = { padding: '8px 10px', fontSize: 11 };
  const inputStyle = {
    background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 12px',
    color: 'var(--text)', fontSize: 13, width: '100%', outline: 'none',
  };
  const selectStyle = { ...inputStyle, cursor: 'pointer' };
  const btnPrimary = {
    background: '#25D366', color: '#000', border: 'none', borderRadius: 6, padding: '8px 16px',
    fontWeight: 700, fontSize: 12, cursor: 'pointer',
  };
  const btnOutline = {
    background: 'transparent', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 16px',
    color: 'var(--text-secondary)', fontWeight: 600, fontSize: 12, cursor: 'pointer',
  };
  const btnDanger = {
    background: 'transparent', border: '1px solid var(--badge-red-bg)', borderRadius: 6, padding: '4px 10px',
    color: 'var(--red)', fontWeight: 600, fontSize: 11, cursor: 'pointer',
  };

  if (dateLoading || loadingAccounts) {
    return <div style={{ padding: 40, textAlign: 'center', color: 'var(--dim)' }}>Loading...</div>;
  }

  return (
    <div className="fade-in">
      <h2 style={{ margin: '0 0 20px', fontSize: 18, fontWeight: 700 }}>WABA Management</h2>

      {/* ════════════════════════════════════════════════════════════════════ */}
      {/* Section A: Message Templates                                       */}
      {/* ════════════════════════════════════════════════════════════════════ */}
      <div style={{ ...card, marginBottom: 20 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <div>
            <div style={{ fontSize: 15, fontWeight: 700 }}>Message Templates</div>
            {lastSynced && (
              <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 2 }}>
                Last synced: {new Date(lastSynced).toLocaleString('id-ID', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}
              </div>
            )}
          </div>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            {canSyncTemplates && (
              <div style={{ display: 'flex', gap: 2 }}>
                <button
                  style={{ ...btnOutline, fontSize: 11, padding: '6px 12px', borderRadius: '6px 0 0 6px', opacity: syncing ? 0.6 : 1 }}
                  disabled={syncing}
                  onClick={() => handleSync('cron')}
                  title="Sync templates + last 3 days analytics"
                >
                  {syncing ? 'Syncing...' : 'Sync'}
                </button>
                <button
                  style={{ ...btnOutline, fontSize: 10, padding: '6px 8px', borderRadius: '0 6px 6px 0', borderLeft: 'none', opacity: syncing ? 0.6 : 1 }}
                  disabled={syncing}
                  onClick={() => { if (confirm('Full backfill syncs 90 days analytics data. This may take 2-3 minutes. Continue?')) handleSync('full'); }}
                  title="Full backfill: sync templates + 90 days analytics"
                >
                  90d
                </button>
              </div>
            )}
            <button style={btnPrimary} onClick={() => setShowCreateForm(!showCreateForm)}>
              {showCreateForm ? 'Cancel' : '+ Create Template'}
            </button>
          </div>
        </div>

        {syncNotice && (
          <div style={{
            marginBottom: 12,
            padding: '10px 12px',
            borderRadius: 8,
            border: syncNotice.tone === 'error'
              ? '1px solid #991b1b'
              : syncNotice.tone === 'warning'
                ? '1px solid #a16207'
                : '1px solid #065f46',
            background: syncNotice.tone === 'error'
              ? 'rgba(127,29,29,0.15)'
              : syncNotice.tone === 'warning'
                ? 'rgba(161,98,7,0.15)'
                : 'rgba(6,95,70,0.15)',
            color: syncNotice.tone === 'error'
              ? '#fca5a5'
              : syncNotice.tone === 'warning'
                ? '#fde68a'
                : '#86efac',
            fontSize: 12,
            lineHeight: 1.6,
          }}>
            {syncNotice.text}
          </div>
        )}

        {/* ── Create Form with Live Preview ── */}
        {showCreateForm && (
          <div style={{ background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 8, padding: 16, marginBottom: 16 }}>
            <div style={{ fontSize: 13, fontWeight: 700, marginBottom: 12 }}>New Template</div>
            <div style={{ display: 'flex', gap: 20 }}>
              {/* ── Left: Form Fields ── */}
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12, marginBottom: 12 }}>
                  <div>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', marginBottom: 4, display: 'block' }}>Name</label>
                    <input style={{ ...inputStyle, borderColor: nameErrors.length > 0 ? 'var(--red)' : 'var(--border)' }} value={formName} onChange={e => setFormName(e.target.value)}
                      placeholder="e.g. promo_january" />
                    {nameErrors.map((e, i) => <div key={i} style={{ color: 'var(--red)', fontSize: 11, marginTop: 4 }}>{e}</div>)}
                  </div>
                  <div>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', marginBottom: 4, display: 'block' }}>Category</label>
                    <select style={selectStyle} value={formCategory} onChange={e => setFormCategory(e.target.value as any)}>
                      <option value="MARKETING">Marketing</option>
                      <option value="UTILITY">Utility</option>
                      <option value="AUTHENTICATION">Authentication</option>
                    </select>
                  </div>
                  <div>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', marginBottom: 4, display: 'block' }}>Language</label>
                    <select style={selectStyle} value={formLanguage} onChange={e => setFormLanguage(e.target.value)}>
                      <option value="id">Indonesian (id)</option>
                      <option value="en">English (en)</option>
                      <option value="en_US">English US (en_US)</option>
                    </select>
                  </div>
                </div>

                {activeWabaAccounts.length > 0 && (
                  <div style={{ marginBottom: 12 }}>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', marginBottom: 4, display: 'block' }}>
                      WABA Account
                    </label>
                    <select
                      style={selectStyle}
                      value={selectedCreateWabaId}
                      onChange={e => setSelectedCreateWabaId(e.target.value)}
                    >
                      {activeWabaAccounts.map((account) => (
                        <option key={account.waba_id} value={account.waba_id}>
                          {account.waba_name}
                        </option>
                      ))}
                    </select>
                    {hasMultipleWabaAccounts && (
                      <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 4 }}>
                        Template baru akan dibuat pada WABA account yang dipilih.
                      </div>
                    )}
                  </div>
                )}

                <div style={{ marginBottom: 12 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase' }}>Header (optional)</label>
                    {formHeader.length > 0 && <span style={{ fontSize: 10, color: formHeader.length > 60 ? 'var(--red)' : 'var(--text-muted)' }}>{formHeader.length}/60</span>}
                  </div>
                  <input style={{ ...inputStyle, borderColor: headerErrors.length > 0 ? 'var(--red)' : 'var(--border)' }} value={formHeader} onChange={e => setFormHeader(e.target.value)}
                    placeholder="Header text" />
                  {headerErrors.map((e, i) => <div key={i} style={{ color: 'var(--red)', fontSize: 11, marginTop: 4 }}>{e}</div>)}
                </div>

                <div style={{ marginBottom: 12 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase' }}>Body *</label>
                    <span style={{ fontSize: 10, color: formBody.length > 1024 ? 'var(--red)' : 'var(--text-muted)' }}>{formBody.length}/1024</span>
                  </div>
                  <textarea ref={bodyRef} style={{ ...inputStyle, minHeight: 80, resize: 'vertical', borderColor: bodyErrors.length > 0 ? 'var(--red)' : 'var(--border)' }} value={formBody}
                    onChange={e => setFormBody(e.target.value)}
                    placeholder="Hi {{1}}, check out our latest promo! Use code {{2}} for discount." />
                  {bodyErrors.map((e, i) => <div key={i} style={{ color: 'var(--red)', fontSize: 11, marginTop: 4 }}>{e}</div>)}
                  {/* Formatting toolbar */}
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 2, marginTop: 6, position: 'relative' }}>
                    {/* Emoji picker */}
                    <div ref={emojiPickerRef} style={{ position: 'relative' }}>
                      <button type="button" onClick={() => setShowEmojiPicker(!showEmojiPicker)} title="Emoji"
                        style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, width: 30, height: 28, cursor: 'pointer', color: 'var(--text-secondary)', fontSize: 16, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                        😊
                      </button>
                      {showEmojiPicker && (
                        <div style={{ position: 'absolute', bottom: 36, left: 0, zIndex: 100 }}>
                          <EmojiPicker onEmojiClick={insertEmoji} theme="dark" width={320} height={400} searchPlaceHolder="Search emoji..." skinTonesDisabled previewConfig={{ showPreview: false }} />
                        </div>
                      )}
                    </div>
                    <button type="button" onClick={() => wrapSelection('*', '*')} title="Bold"
                      style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, width: 30, height: 28, cursor: 'pointer', color: 'var(--text-secondary)', fontSize: 14, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      B
                    </button>
                    <button type="button" onClick={() => wrapSelection('_', '_')} title="Italic"
                      style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, width: 30, height: 28, cursor: 'pointer', color: 'var(--text-secondary)', fontSize: 14, fontStyle: 'italic', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      I
                    </button>
                    <button type="button" onClick={() => wrapSelection('~', '~')} title="Strikethrough"
                      style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, width: 30, height: 28, cursor: 'pointer', color: 'var(--text-secondary)', fontSize: 14, textDecoration: 'line-through', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      S
                    </button>
                    <button type="button" onClick={() => wrapSelection('```', '```')} title="Monospace"
                      style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, width: 30, height: 28, cursor: 'pointer', color: 'var(--text-secondary)', fontSize: 12, fontFamily: 'monospace', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      {'</>'}
                    </button>
                    <div style={{ width: 1, height: 20, background: 'var(--border)', margin: '0 4px' }} />
                    <button type="button" onClick={addVariable} title="Add variable"
                      style={{ background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, height: 28, padding: '0 10px', cursor: 'pointer', color: '#60a5fa', fontSize: 11, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 4 }}>
                      + Add variable
                    </button>
                  </div>
                </div>

                {/* Variable Samples — auto-detected from body */}
                {detectedVars.length > 0 && (
                  <div style={{ marginBottom: 12, background: '#0d1526', border: '1px solid var(--border)', borderRadius: 6, padding: 12 }}>
                    <div style={{ fontSize: 11, fontWeight: 700, marginBottom: 4 }}>Variable Samples</div>
                    <div style={{ fontSize: 10, color: 'var(--text-muted)', marginBottom: 10 }}>
                      Provide sample content for each variable to help Meta review your template.
                    </div>
                    {detectedVars.map(v => {
                      const key = v.replace(/[{}]/g, '');
                      return (
                        <div key={key} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                          <span style={{
                            background: 'var(--border)', borderRadius: 4, padding: '4px 10px', fontSize: 12,
                            fontFamily: 'monospace', color: 'var(--text-secondary)', minWidth: 50, textAlign: 'center', flexShrink: 0,
                          }}>{v}</span>
                          <input style={inputStyle} value={varSamples[key] || ''}
                            onChange={e => setVarSamples(prev => ({ ...prev, [key]: e.target.value }))}
                            placeholder={`Enter sample for ${v}`} />
                        </div>
                      );
                    })}
                  </div>
                )}

                <div style={{ marginBottom: 12 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                    <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase' }}>Footer (optional)</label>
                    {formFooter.length > 0 && <span style={{ fontSize: 10, color: formFooter.length > 60 ? 'var(--red)' : 'var(--text-muted)' }}>{formFooter.length}/60</span>}
                  </div>
                  <input style={{ ...inputStyle, borderColor: footerErrors.length > 0 ? 'var(--red)' : 'var(--border)' }} value={formFooter} onChange={e => setFormFooter(e.target.value)}
                    placeholder="e.g. Reply STOP to unsubscribe" />
                  {footerErrors.map((e, i) => <div key={i} style={{ color: 'var(--red)', fontSize: 11, marginTop: 4 }}>{e}</div>)}
                </div>

                <div style={{ marginBottom: 12 }}>
                  <label style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', marginBottom: 4, display: 'block' }}>Quick Reply Buttons (optional, max 10, 25 chars each)</label>
                  {[0, 1, 2].map(i => (
                    <input key={i} style={{ ...inputStyle, marginBottom: 6, borderColor: formButtons[i]?.trim()?.length > 25 ? 'var(--red)' : 'var(--border)' }}
                      value={formButtons[i] || ''} onChange={e => {
                        const next = [...formButtons];
                        next[i] = e.target.value;
                        setFormButtons(next);
                      }}
                      placeholder={`Button ${i + 1} text`} />
                  ))}
                  {buttonErrors.map((e, i) => <div key={i} style={{ color: 'var(--red)', fontSize: 11, marginTop: 2 }}>{e}</div>)}
                </div>

                {/* Authentication category info */}
                {formCategory === 'AUTHENTICATION' && (
                  <div style={{ background: '#1e1533', border: '1px solid #6b21a8', borderRadius: 6, padding: 10, marginBottom: 12, fontSize: 11, color: '#c084fc' }}>
                    Authentication templates have a fixed body format set by Meta: <strong>{'"{{1}} is your verification code."'}</strong> Your body text will be replaced.
                  </div>
                )}

                {formError && <div style={{ color: 'var(--red)', fontSize: 12, marginBottom: 12 }}>{formError}</div>}

                <div style={{ display: 'flex', gap: 8 }}>
                  <button style={{ ...btnPrimary, opacity: hasValidationErrors || creating ? 0.4 : 1, cursor: hasValidationErrors || creating ? 'not-allowed' : 'pointer' }}
                    onClick={handleCreate} disabled={hasValidationErrors || creating}>
                    {creating ? 'Creating...' : 'Submit Template'}
                  </button>
                  <button style={btnOutline} onClick={() => setShowCreateForm(false)}>Cancel</button>
                </div>

                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 10 }}>
                  New templates go to PENDING status and require Meta review (usually minutes to hours).
                </div>
              </div>

              {/* ── Right: WhatsApp Chat Preview ── */}
              <div style={{ width: 320, flexShrink: 0 }}>
                <div style={{ fontSize: 10, color: 'var(--dim)', textTransform: 'uppercase', fontWeight: 600, marginBottom: 8 }}>Template Preview</div>
                {/* Phone frame */}
                <div style={{ background: '#e5ddd5', borderRadius: 12, padding: 16, minHeight: 200, position: 'relative' }}>
                  {/* Chat wallpaper pattern */}
                  <div style={{ position: 'absolute', inset: 0, borderRadius: 12, opacity: 0.05, background: 'url("data:image/svg+xml,%3Csvg width=\'40\' height=\'40\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cpath d=\'M20 0L0 20h10L20 10l10 10h10z\' fill=\'%23000\'/%3E%3C/svg%3E")' }} />
                  {/* Message bubble */}
                  <div style={{ position: 'relative', background: '#fff', borderRadius: '0 8px 8px 8px', padding: '8px 10px', maxWidth: '100%', boxShadow: '0 1px 2px rgba(0,0,0,0.13)' }}>
                    {/* Header */}
                    {formHeader.trim() && (
                      <div style={{ fontSize: 14, fontWeight: 700, color: '#1a1a1a', marginBottom: 4, lineHeight: 1.3 }}>
                        {formHeader}
                      </div>
                    )}
                    {/* Body */}
                    <div style={{ fontSize: 13, color: '#303030', lineHeight: 1.45, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                      {previewBody ? renderWaFormatted(previewBody) : <span style={{ color: '#999' }}>Message body will appear here...</span>}
                    </div>
                    {/* Footer */}
                    {formFooter.trim() && (
                      <div style={{ fontSize: 11, color: '#8c8c8c', marginTop: 6 }}>
                        {formFooter}
                      </div>
                    )}
                    {/* Timestamp */}
                    <div style={{ textAlign: 'right', marginTop: 2 }}>
                      <span style={{ fontSize: 10, color: '#8c8c8c' }}>
                        {new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                  </div>
                  {/* Quick reply buttons */}
                  {formButtons.filter(b => b.trim()).length > 0 && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginTop: 4 }}>
                      {formButtons.filter(b => b.trim()).map((btn, i) => (
                        <div key={i} style={{
                          background: '#fff', borderRadius: 8, padding: '8px 12px', textAlign: 'center',
                          fontSize: 13, color: '#00a5f4', fontWeight: 500, boxShadow: '0 1px 2px rgba(0,0,0,0.13)',
                          cursor: 'default',
                        }}>
                          {btn}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
                {/* Category & Language info */}
                <div style={{ marginTop: 10, fontSize: 10, color: 'var(--dim)' }}>
                  <div><strong>Category:</strong> {formCategory}</div>
                  <div><strong>Language:</strong> {formLanguage}</div>
                  {formName && <div><strong>Name:</strong> {formName.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')}</div>}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── Template List ── */}
        {templateError && <div style={{ color: 'var(--red)', fontSize: 12, marginBottom: 12 }}>{templateError}</div>}
        {templateAnalyticsError && (
          <div style={{ color: 'var(--yellow)', fontSize: 12, marginBottom: 12 }}>
            Analytics template tidak bisa dimuat: {templateAnalyticsError}
          </div>
        )}

        {/* Search + Filter toggles */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12, flexWrap: 'wrap' }}>
          <input
            type="text"
            placeholder="Search templates..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            style={{
              background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 6,
              padding: '5px 12px', color: 'var(--text)', fontSize: 11, width: 180,
              outline: 'none',
            }}
          />
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12, flexWrap: 'wrap' }}>
          {autoGeneratedCount > 0 && (
            <button
              onClick={() => setShowAutoGenerated(!showAutoGenerated)}
              style={{
                background: showAutoGenerated ? '#1e3a5f' : 'transparent',
                border: `1px solid ${showAutoGenerated ? 'var(--accent)' : 'var(--border)'}`,
                borderRadius: 6, padding: '5px 12px', cursor: 'pointer',
                color: showAutoGenerated ? '#60a5fa' : 'var(--dim)',
                fontSize: 11, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 6,
              }}
            >
              <span style={{
                display: 'inline-block', width: 14, height: 14, borderRadius: 3,
                border: `1.5px solid ${showAutoGenerated ? 'var(--accent)' : 'var(--text-muted)'}`,
                background: showAutoGenerated ? 'var(--accent)' : 'transparent',
                lineHeight: '12px', textAlign: 'center', fontSize: 10, color: '#fff',
              }}>{showAutoGenerated ? '✓' : ''}</span>
              Show auto-generated CTWA templates ({autoGeneratedCount})
            </button>
          )}
          <button
            onClick={() => setShowOnlySent(!showOnlySent)}
            style={{
              background: showOnlySent ? 'var(--badge-green-bg)' : 'transparent',
              border: `1px solid ${showOnlySent ? 'var(--green)' : 'var(--border)'}`,
              borderRadius: 6, padding: '5px 12px', cursor: 'pointer',
              color: showOnlySent ? 'var(--green)' : 'var(--dim)',
              fontSize: 11, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 6,
            }}
          >
            <span style={{
              display: 'inline-block', width: 14, height: 14, borderRadius: 3,
              border: `1.5px solid ${showOnlySent ? 'var(--green)' : 'var(--text-muted)'}`,
              background: showOnlySent ? 'var(--green)' : 'transparent',
              lineHeight: '12px', textAlign: 'center', fontSize: 10, color: '#fff',
            }}>{showOnlySent ? '✓' : ''}</span>
            Sent &gt; 0 only
          </button>
          <span style={{ fontSize: 10, color: 'var(--text-muted)' }}>
            Showing {filteredTemplates.length} of {templates.length} templates
          </span>
        </div>

        {/* Tag filter chips */}
        {allTags.length > 0 && (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 10 }}>
            <span style={{ fontSize: 10, color: 'var(--text-muted)', alignSelf: 'center', marginRight: 4 }}>Tags:</span>
            {allTags.map(tag => (
              <button key={tag} onClick={() => setFilterTag(filterTag === tag ? null : tag)}
                style={{
                  background: filterTag === tag ? 'var(--accent)' : 'var(--bg-deep)',
                  color: filterTag === tag ? '#fff' : 'var(--text-secondary)',
                  border: `1px solid ${filterTag === tag ? 'var(--accent)' : 'var(--border)'}`,
                  borderRadius: 12, padding: '2px 10px', fontSize: 10, fontWeight: 600,
                  cursor: 'pointer', transition: 'all 0.15s',
                }}>
                {tag}
              </button>
            ))}
            {filterTag && (
              <button onClick={() => setFilterTag(null)}
                style={{ background: 'transparent', border: 'none', color: 'var(--red)', fontSize: 10, cursor: 'pointer', padding: '2px 6px' }}>
                ✕ Clear
              </button>
            )}
          </div>
        )}

        {loadingTemplates && templates.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 24, color: 'var(--dim)' }}>Loading templates...</div>
        ) : filteredTemplates.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 24, color: 'var(--dim)' }}>
            {templates.length > 0 ? 'All templates are auto-generated. Toggle above to show them.' : 'No templates found'}
          </div>
        ) : (
          <>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 950 }}>
                <thead>
                  <tr style={{ borderBottom: '2px solid var(--border)' }}>
                    <th style={{ ...thStyle, textAlign: 'left' }}>Name</th>
                    {hasMultipleWabaAccounts && <th style={{ ...thStyle, textAlign: 'left' }}>WABA</th>}
                    <th style={{ ...thStyle, textAlign: 'left' }}>Category</th>
                    <th style={{ ...thStyle, textAlign: 'center' }}>Status</th>
                    <th style={{ ...thStyle, textAlign: 'center' }}>Language</th>
                    <th style={{ ...thStyle, textAlign: 'left' }}>Body Preview</th>
                    <th style={{ ...thStyle, textAlign: 'right' }}>Sent</th>
                    <th style={{ ...thStyle, textAlign: 'right' }}>Click/Read</th>
                    <th style={{ ...thStyle, textAlign: 'right' }}>Reply/Read</th>
                    <th style={{ ...thStyle, textAlign: 'center' }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredTemplates.map(t => {
                    const ss = STATUS_STYLE[t.status] || STATUS_STYLE.PAUSED;
                    const cs = CATEGORY_STYLE[t.category] || CATEGORY_STYLE.UTILITY;
                    const bodyText = getBodyText(t.components);
                    const preview = bodyText.length > 80 ? bodyText.substring(0, 80) + '...' : bodyText;
                    const isExpanded = expandedTemplate === t.id;
                    const metrics = templateAnalytics[t.id];
                    return (
                      <React.Fragment key={t.id}>
                        <tr style={{ borderBottom: isExpanded ? 'none' : '1px solid var(--border)', cursor: 'pointer', transition: 'background 0.15s' }}
                          onClick={() => setExpandedTemplate(isExpanded ? null : t.id)}
                          onMouseEnter={e => (e.currentTarget.style.background = 'var(--card-hover)')}
                          onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}>
                          <td style={{ ...tdStyle, fontWeight: 600, fontFamily: 'monospace' }}>
                            <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                              <span style={{ fontSize: 9, color: 'var(--text-muted)' }}>{isExpanded ? '▼' : '▶'}</span>
                              {t.name}
                              <button
                                title="Copy template name"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  navigator.clipboard.writeText(t.name);
                                  setCopiedName(t.id);
                                  setTimeout(() => setCopiedName(prev => prev === t.id ? null : prev), 1500);
                                }}
                                style={{ background: 'transparent', border: 'none', cursor: 'pointer', padding: '0 2px', fontSize: 12, color: copiedName === t.id ? 'var(--green)' : 'var(--text-muted)', lineHeight: 1 }}
                              >
                                {copiedName === t.id ? '✓' : '📋'}
                              </button>
                            </span>
                            {hasMultipleWabaAccounts && (
                              <div style={{ marginTop: 3, fontSize: 10, color: 'var(--text-muted)', fontFamily: 'sans-serif' }}>
                                {wabaNameById[t.waba_id] || t.waba_id}
                              </div>
                            )}
                            {/* Tag badges */}
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 3, marginTop: 3 }}>
                              {(t.tags || []).map(tag => (
                                <span key={tag} style={{
                                  display: 'inline-flex', alignItems: 'center', gap: 2,
                                  background: '#1e3a5f', color: '#60a5fa', borderRadius: 8,
                                  padding: '1px 6px', fontSize: 9, fontWeight: 600, fontFamily: 'sans-serif',
                                }}>
                                  {tag}
                                  <button onClick={(e) => {
                                    e.stopPropagation();
                                    handleUpdateTags(t.id, (t.tags || []).filter(x => x !== tag));
                                  }} style={{
                                    background: 'transparent', border: 'none', color: '#60a5fa',
                                    cursor: 'pointer', padding: 0, fontSize: 10, lineHeight: 1, opacity: 0.7,
                                  }}>×</button>
                                </span>
                              ))}
                              {editingTagId === t.id ? (
                                <input
                                  autoFocus
                                  value={tagInput}
                                  onChange={e => setTagInput(e.target.value)}
                                  onKeyDown={e => {
                                    if (e.key === 'Enter' && tagInput.trim()) {
                                      e.stopPropagation();
                                      const newTag = tagInput.trim().toLowerCase();
                                      if (!(t.tags || []).includes(newTag)) {
                                        handleUpdateTags(t.id, [...(t.tags || []), newTag]);
                                      }
                                      setTagInput('');
                                      setEditingTagId(null);
                                    } else if (e.key === 'Escape') {
                                      setTagInput('');
                                      setEditingTagId(null);
                                    }
                                  }}
                                  onBlur={() => { setTagInput(''); setEditingTagId(null); }}
                                  onClick={e => e.stopPropagation()}
                                  placeholder="tag..."
                                  style={{
                                    width: 60, background: 'var(--bg-deep)', border: '1px solid var(--border)',
                                    borderRadius: 8, padding: '1px 6px', fontSize: 9, color: 'var(--text)',
                                    outline: 'none', fontFamily: 'sans-serif',
                                  }}
                                />
                              ) : (
                                <button onClick={(e) => {
                                  e.stopPropagation();
                                  setEditingTagId(t.id);
                                  setTagInput('');
                                }} style={{
                                  background: 'var(--bg-deep)', border: '1px solid var(--border)', borderRadius: 8,
                                  padding: '1px 6px', fontSize: 9, color: 'var(--text-muted)', cursor: 'pointer',
                                  fontFamily: 'sans-serif',
                                }}>+</button>
                              )}
                            </div>
                          </td>
                          {hasMultipleWabaAccounts && (
                            <td style={{ ...tdStyle, color: 'var(--text-secondary)' }}>
                              {wabaNameById[t.waba_id] || t.waba_id}
                            </td>
                          )}
                          <td style={tdStyle}>
                            <span style={{ padding: '2px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700, background: cs.bg, color: cs.color }}>
                              {t.category}
                            </span>
                          </td>
                          <td style={{ ...tdStyle, textAlign: 'center' }}>
                            <span style={{ padding: '2px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700, background: ss.bg, color: ss.color }}>
                              {t.status}
                            </span>
                          </td>
                          <td style={{ ...tdStyle, textAlign: 'center', color: 'var(--text-secondary)' }}>{t.language}</td>
                          <td style={{ ...tdStyle, color: 'var(--text-secondary)', maxWidth: 300 }}>{preview}</td>
                          <td style={{ ...tdStyle, textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                            {metrics?.sent ? metrics.sent.toLocaleString() : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                          </td>
                          <td style={{ ...tdStyle, textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                            {metrics?.read && metrics.read > 0 ? (
                              <span style={{ padding: '2px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700, background: '#1e3a5f', color: '#60a5fa' }}>
                                {(metrics.clicked / metrics.read * 100).toFixed(1)}%
                              </span>
                            ) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                          </td>
                          <td style={{ ...tdStyle, textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                            {metrics?.read && metrics.read > 0 ? (
                              <span style={{ padding: '2px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700, background: 'var(--badge-green-bg)', color: 'var(--green)' }}>
                                {(metrics.replied / metrics.read * 100).toFixed(1)}%
                              </span>
                            ) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                          </td>
                          <td style={{ ...tdStyle, textAlign: 'center' }}>
                            <button style={btnDanger} onClick={(e) => { e.stopPropagation(); handleDelete(t); }}
                              disabled={deleting === t.id}>
                              {deleting === t.id ? '...' : 'Delete'}
                            </button>
                          </td>
                        </tr>
                        {isExpanded && (
                          <tr style={{ borderBottom: '1px solid var(--border)' }}>
                            <td colSpan={hasMultipleWabaAccounts ? 10 : 9} style={{ padding: '12px 10px 16px' }}>
                              <TemplatePreview template={t} renderWaFormatted={renderWaFormatted} analytics={metrics} />
                            </td>
                          </tr>
                        )}
                      </React.Fragment>
                    );
                  })}
                </tbody>
              </table>
            </div>

          </>
        )}
      </div>

      {/* ════════════════════════════════════════════════════════════════════ */}
      {/* Section B: WABA Promotion Analysis                                 */}
      {/* ════════════════════════════════════════════════════════════════════ */}
      <div style={{ ...card }}>
        <div style={{ fontSize: 15, fontWeight: 700, marginBottom: 12 }}>WABA Promotion Analysis</div>

        {loadingAnalytics ? (
          <div style={{ textAlign: 'center', padding: 24, color: 'var(--dim)' }}>Loading analytics...</div>
        ) : wabaAnalysis.rows.length === 0 ? (
          <div style={{ textAlign: 'center', padding: 24, color: 'var(--dim)' }}>No WABA data for selected period</div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12, minWidth: 800 }}>
              <thead>
                <tr style={{ borderBottom: '2px solid var(--border)' }}>
                  {['Date', 'MM Sent', 'MM Delivered', 'Delivery Rate', 'Order Qty', 'WABA MM Cost', 'Total Purchase', 'Cost/Order'].map(h => (
                    <th key={h} style={{ padding: '8px 10px', textAlign: h === 'Date' ? 'left' : 'right', color: 'var(--dim)', fontWeight: 600, fontSize: 10, textTransform: 'uppercase' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {wabaAnalysis.rows.map(r => (
                  <tr key={r.date} style={{ borderBottom: '1px solid var(--border)' }}>
                    <td style={{ padding: '8px 10px', fontWeight: 600 }}>{r.dateLabel}</td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                      {r.sent > 0 ? r.sent.toLocaleString() : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                      {r.delivered > 0 ? r.delivered.toLocaleString() : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                    <td style={{ padding: '8px 10px', textAlign: 'right' }}>
                      {r.sent > 0 ? (
                        <span style={{
                          padding: '2px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700,
                          background: r.deliveryRate >= 95 ? 'var(--badge-green-bg)' : r.deliveryRate >= 85 ? 'var(--badge-yellow-bg)' : 'var(--badge-red-bg)',
                          color: r.deliveryRate >= 95 ? 'var(--green)' : r.deliveryRate >= 85 ? 'var(--yellow)' : 'var(--red)',
                        }}>{r.deliveryRate.toFixed(1)}%</span>
                      ) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 600 }}>
                      {r.orders > 0 ? r.orders.toLocaleString() : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, color: '#25D366' }}>
                      {r.cost > 0 ? fmtRupiah(r.cost) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                      {r.revenue > 0 ? fmtRupiah(r.revenue) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                    <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11 }}>
                      {r.orders > 0 ? fmtRupiah(r.costPerOrder) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                    </td>
                  </tr>
                ))}
                <tr style={{ borderTop: '2px solid var(--border)', background: 'var(--bg)' }}>
                  <td style={{ padding: '8px 10px', fontWeight: 700, fontSize: 11 }}>TOTAL</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 700 }}>{wabaAnalysis.totals.sent.toLocaleString()}</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 700 }}>{wabaAnalysis.totals.delivered.toLocaleString()}</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right' }}>
                    {wabaAnalysis.totals.sent > 0 ? (
                      <span style={{
                        padding: '2px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700,
                        background: wabaAnalysis.totals.deliveryRate >= 95 ? 'var(--badge-green-bg)' : 'var(--badge-yellow-bg)',
                        color: wabaAnalysis.totals.deliveryRate >= 95 ? 'var(--green)' : 'var(--yellow)',
                      }}>{wabaAnalysis.totals.deliveryRate.toFixed(1)}%</span>
                    ) : <span style={{ color: 'var(--text-muted)' }}>—</span>}
                  </td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 700 }}>{wabaAnalysis.totals.orders.toLocaleString()}</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 700, color: '#25D366' }}>{fmtRupiah(wabaAnalysis.totals.cost)}</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 700 }}>{fmtRupiah(wabaAnalysis.totals.revenue)}</td>
                  <td style={{ padding: '8px 10px', textAlign: 'right', fontFamily: 'monospace', fontSize: 11, fontWeight: 700 }}>{wabaAnalysis.totals.orders > 0 ? fmtRupiah(wabaAnalysis.totals.costPerOrder) : <span style={{ color: 'var(--text-muted)' }}>—</span>}</td>
                </tr>
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
