// lib/ppic-actions.ts
'use server';

import { createServiceSupabase, createServerSupabase } from './supabase-server';
import { recordStockIn, createBatch } from './warehouse-ledger-actions';

// ============================================================
// AUTH HELPER (same pattern as warehouse-ledger-actions)
// ============================================================

async function getCurrentUserId(): Promise<string | null> {
  try {
    const supabase = createServerSupabase();
    const { data: { user } } = await supabase.auth.getUser();
    return user?.id || null;
  } catch {
    return null;
  }
}

// ============================================================
// PURCHASE ORDER — CRUD
// ============================================================

export interface POItem {
  warehouseProductId: number;
  quantityRequested: number;
  unitPrice?: number;
  notes?: string;
}

export interface CreatePOParams {
  vendorId: number;
  entity: string;
  poDate?: string;
  expectedDate?: string;
  notes?: string;
  items: POItem[];
}

export async function createPurchaseOrder(params: CreatePOParams) {
  const { vendorId, entity, poDate, expectedDate, notes, items } = params;
  if (!items || items.length === 0) throw new Error('PO harus memiliki minimal 1 item');

  const svc = createServiceSupabase();
  const userId = await getCurrentUserId();

  // Insert PO header (po_number auto-generated by trigger)
  const { data: po, error: poErr } = await svc
    .from('warehouse_purchase_orders')
    .insert({
      po_number: '', // trigger will fill
      vendor_id: vendorId,
      entity,
      po_date: poDate || new Date().toISOString().slice(0, 10),
      expected_date: expectedDate || null,
      status: 'draft',
      notes: notes || null,
      created_by: userId,
    })
    .select('id, po_number')
    .single();
  if (poErr) throw poErr;

  // Insert items
  const itemRows = items.map(item => ({
    po_id: po.id,
    warehouse_product_id: item.warehouseProductId,
    quantity_requested: item.quantityRequested,
    quantity_received: 0,
    unit_price: item.unitPrice || 0,
    notes: item.notes || null,
  }));

  const { error: itemErr } = await svc
    .from('warehouse_po_items')
    .insert(itemRows);
  if (itemErr) throw itemErr;

  return po;
}

export async function getPurchaseOrders(filters?: {
  status?: string;
  vendorId?: number;
  entity?: string;
  dateFrom?: string;
  dateTo?: string;
  limit?: number;
}) {
  const svc = createServiceSupabase();
  let query = svc
    .from('warehouse_purchase_orders')
    .select(`
      *,
      warehouse_vendors!inner(id, name),
      warehouse_po_items(
        id, warehouse_product_id, quantity_requested, quantity_received, unit_price, notes,
        warehouse_products(id, name, category, entity, unit)
      )
    `)
    .order('po_date', { ascending: false });

  if (filters?.status) query = query.eq('status', filters.status);
  if (filters?.vendorId) query = query.eq('vendor_id', filters.vendorId);
  if (filters?.entity) query = query.eq('entity', filters.entity);
  if (filters?.dateFrom) query = query.gte('po_date', filters.dateFrom);
  if (filters?.dateTo) query = query.lte('po_date', filters.dateTo);
  query = query.limit(filters?.limit || 100);

  const { data, error } = await query;
  if (error) throw error;
  return data || [];
}

export async function getPurchaseOrderDetail(poId: number) {
  const svc = createServiceSupabase();
  const { data, error } = await svc
    .from('warehouse_purchase_orders')
    .select(`
      *,
      warehouse_vendors(id, name, pic_name, phone),
      warehouse_po_items(
        id, warehouse_product_id, quantity_requested, quantity_received, unit_price, notes,
        warehouse_products(id, name, category, entity, unit, hpp)
      ),
      profiles!warehouse_purchase_orders_created_by_fkey(full_name, email)
    `)
    .eq('id', poId)
    .single();
  if (error) throw error;
  return data;
}

export async function submitPurchaseOrder(poId: number) {
  const svc = createServiceSupabase();

  const { data: po } = await svc
    .from('warehouse_purchase_orders')
    .select('id, status')
    .eq('id', poId)
    .single();
  if (!po) throw new Error('PO tidak ditemukan');
  if (po.status !== 'draft') throw new Error('Hanya PO draft yang bisa disubmit');

  // Ensure PO has items
  const { count } = await svc
    .from('warehouse_po_items')
    .select('id', { count: 'exact', head: true })
    .eq('po_id', poId);
  if (!count || count === 0) throw new Error('PO harus memiliki minimal 1 item');

  const { data, error } = await svc
    .from('warehouse_purchase_orders')
    .update({ status: 'submitted' })
    .eq('id', poId)
    .select()
    .single();
  if (error) throw error;
  return data;
}

export async function cancelPurchaseOrder(poId: number) {
  const svc = createServiceSupabase();

  const { data: po } = await svc
    .from('warehouse_purchase_orders')
    .select('id, status')
    .eq('id', poId)
    .single();
  if (!po) throw new Error('PO tidak ditemukan');
  if (!['draft', 'submitted'].includes(po.status)) throw new Error('Hanya PO draft/submitted yang bisa dibatalkan');

  const { data, error } = await svc
    .from('warehouse_purchase_orders')
    .update({ status: 'cancelled' })
    .eq('id', poId)
    .select()
    .single();
  if (error) throw error;
  return data;
}

// ============================================================
// PURCHASE ORDER — RECEIVE ITEMS
// ============================================================

export interface ReceiveItem {
  poItemId: number;
  quantityReceived: number;
  batchCode: string;
  expiredDate?: string | null;
}

export async function receivePOItems(poId: number, receivedItems: ReceiveItem[]) {
  if (!receivedItems || receivedItems.length === 0) throw new Error('Tidak ada item yang diterima');

  const svc = createServiceSupabase();

  // Get PO with items
  const { data: po } = await svc
    .from('warehouse_purchase_orders')
    .select(`
      id, status, po_number,
      warehouse_po_items(id, warehouse_product_id, quantity_requested, quantity_received)
    `)
    .eq('id', poId)
    .single();
  if (!po) throw new Error('PO tidak ditemukan');
  if (!['submitted', 'partial'].includes(po.status)) throw new Error('PO harus berstatus submitted atau partial');

  const results: any[] = [];

  for (const item of receivedItems) {
    if (item.quantityReceived <= 0) continue;

    // Find matching PO item
    const poItem = (po.warehouse_po_items || []).find((pi: any) => pi.id === item.poItemId);
    if (!poItem) throw new Error(`PO item #${item.poItemId} tidak ditemukan`);

    const remaining = Number(poItem.quantity_requested) - Number(poItem.quantity_received);
    if (item.quantityReceived > remaining) {
      throw new Error(`Qty melebihi sisa (${remaining}) untuk item #${item.poItemId}`);
    }

    // Create batch
    const batch = await createBatch(
      poItem.warehouse_product_id,
      item.batchCode,
      item.expiredDate || null,
      0, // initial qty 0 — we'll use recordStockIn for the ledger entry
    );

    // Record stock in (creates ledger entry + updates batch qty)
    await recordStockIn(
      poItem.warehouse_product_id,
      batch.id,
      item.quantityReceived,
      'purchase_order',
      String(poId),
      `PO ${po.po_number} - batch ${item.batchCode}`,
    );

    // Update PO item received qty
    const newReceived = Number(poItem.quantity_received) + item.quantityReceived;
    await svc
      .from('warehouse_po_items')
      .update({ quantity_received: newReceived })
      .eq('id', item.poItemId);

    results.push({ poItemId: item.poItemId, batchId: batch.id, received: item.quantityReceived });
  }

  // Check if all items fully received → set PO status
  const { data: allItems } = await svc
    .from('warehouse_po_items')
    .select('quantity_requested, quantity_received')
    .eq('po_id', poId);

  const allFullyReceived = (allItems || []).every(
    (i: any) => Number(i.quantity_received) >= Number(i.quantity_requested)
  );
  const anyReceived = (allItems || []).some(
    (i: any) => Number(i.quantity_received) > 0
  );

  const newStatus = allFullyReceived ? 'completed' : anyReceived ? 'partial' : po.status;
  await svc
    .from('warehouse_purchase_orders')
    .update({ status: newStatus })
    .eq('id', poId);

  return { poId, status: newStatus, items: results };
}

// ============================================================
// DEMAND PLANNING
// ============================================================

export async function getDemandPlans(month: number, year: number) {
  const svc = createServiceSupabase();
  const { data, error } = await svc
    .from('warehouse_demand_plans')
    .select(`
      *,
      warehouse_products(id, name, category, entity, unit)
    `)
    .eq('month', month)
    .eq('year', year)
    .order('warehouse_product_id');
  if (error) throw error;
  return data || [];
}

export async function initDemandPlans(month: number, year: number) {
  const svc = createServiceSupabase();

  // Get auto demand from ScaleV (last 6 months average)
  const { data: demandData, error: demandErr } = await svc.rpc('ppic_monthly_demand', { p_months: 6 });
  if (demandErr) throw demandErr;

  // Calculate average monthly demand per product
  const productDemand = new Map<number, { total: number; months: number }>();
  for (const row of (demandData || [])) {
    const existing = productDemand.get(row.warehouse_product_id) || { total: 0, months: 0 };
    existing.total += Number(row.total_qty);
    existing.months += 1;
    productDemand.set(row.warehouse_product_id, existing);
  }

  // Get actual movements for the target month
  const { data: movData, error: movErr } = await svc.rpc('ppic_monthly_movements', { p_months: 12 });
  if (movErr) throw movErr;

  const actualMap = new Map<number, { in: number; out: number }>();
  for (const row of (movData || [])) {
    if (row.yr === year && row.mn === month) {
      actualMap.set(row.warehouse_product_id, {
        in: Number(row.total_in),
        out: Number(row.total_out),
      });
    }
  }

  // Get all active products
  const { data: products } = await svc
    .from('warehouse_products')
    .select('id')
    .eq('is_active', true);

  // Upsert demand plans
  const rows = (products || []).map(p => {
    const demand = productDemand.get(p.id);
    const avgMonthly = demand ? Math.round(demand.total / demand.months) : 0;
    const actual = actualMap.get(p.id);

    return {
      warehouse_product_id: p.id,
      month,
      year,
      auto_demand: avgMonthly,
      actual_in: actual?.in || 0,
      actual_out: actual?.out || 0,
    };
  });

  // Upsert in batches
  for (let i = 0; i < rows.length; i += 50) {
    const batch = rows.slice(i, i + 50);
    const { error } = await svc
      .from('warehouse_demand_plans')
      .upsert(batch, { onConflict: 'warehouse_product_id,month,year' });
    if (error) throw error;
  }

  return { count: rows.length };
}

export async function updateDemandPlan(
  productId: number,
  month: number,
  year: number,
  manualDemand: number | null,
  notes?: string,
) {
  const svc = createServiceSupabase();
  const { data, error } = await svc
    .from('warehouse_demand_plans')
    .upsert({
      warehouse_product_id: productId,
      month,
      year,
      manual_demand: manualDemand,
      notes: notes || null,
    }, { onConflict: 'warehouse_product_id,month,year' })
    .select()
    .single();
  if (error) throw error;
  return data;
}

// ============================================================
// ITO (Inventory Turn Over)
// ============================================================

export async function getITOData(months: number = 6) {
  const svc = createServiceSupabase();

  // Get monthly movements
  const { data: movements, error: movErr } = await svc.rpc('ppic_monthly_movements', { p_months: months });
  if (movErr) throw movErr;

  // Get current stock balance
  const { data: stockData } = await svc.from('v_warehouse_stock_balance').select('*');

  // Get products with HPP
  const { data: products } = await svc
    .from('warehouse_products')
    .select('id, name, category, entity, hpp, unit')
    .eq('is_active', true)
    .order('name');

  // Build product map
  const productMap = new Map<number, any>();
  for (const p of (products || [])) {
    productMap.set(p.id, { ...p, months: [] as any[] });
  }

  // Group movements by product + month
  for (const m of (movements || [])) {
    const prod = productMap.get(m.warehouse_product_id);
    if (prod) {
      prod.months.push({
        year: m.yr,
        month: m.mn,
        total_in: Number(m.total_in),
        total_out: Number(m.total_out),
      });
    }
  }

  // Map stock balances
  const stockMap = new Map<number, number>();
  for (const s of (stockData || [])) {
    stockMap.set(s.product_id, Number(s.current_stock || 0));
  }

  // Calculate ITO per product
  const result = Array.from(productMap.values()).map(prod => {
    const currentStock = stockMap.get(prod.id) || 0;
    const hpp = Number(prod.hpp) || 0;

    // Calculate ITO per month: OUT / avg_inventory
    // For simplicity, ITO = total_out for month (annualized: * 12)
    const monthlyITO = prod.months.map((m: any) => {
      // Simple ITO: monthly OUT qty / current stock (if we had begin/end stock per month)
      // For now: use total_out as monthly turnover indicator
      return {
        year: m.year,
        month: m.month,
        total_out: m.total_out,
        total_in: m.total_in,
        // ITO = (monthly out * 12) / current stock — annualized approximation
        ito: currentStock > 0 ? Math.round((m.total_out * 12 / currentStock) * 100) / 100 : 0,
      };
    });

    return {
      product_id: prod.id,
      product_name: prod.name,
      category: prod.category,
      entity: prod.entity,
      unit: prod.unit,
      hpp,
      current_stock: currentStock,
      months: monthlyITO,
    };
  });

  return result;
}

// ============================================================
// ROP (Reorder Point)
// ============================================================

export async function getROPAnalysis(demandDays: number = 90) {
  const svc = createServiceSupabase();

  // Get avg daily demand
  const { data: demandData, error: demandErr } = await svc.rpc('ppic_avg_daily_demand', { p_days: demandDays });
  if (demandErr) throw demandErr;

  // Get current stock
  const { data: stockData } = await svc.from('v_warehouse_stock_balance').select('*');
  const stockMap = new Map<number, number>();
  for (const s of (stockData || [])) {
    stockMap.set(s.product_id, Number(s.current_stock || 0));
  }

  // Get product ROP config
  const { data: products } = await svc
    .from('warehouse_products')
    .select('id, name, category, entity, unit, lead_time_days, safety_stock_days')
    .eq('is_active', true);

  const productMap = new Map<number, any>();
  for (const p of (products || [])) {
    productMap.set(p.id, p);
  }

  // Build ROP analysis
  const demandMap = new Map<number, number>();
  for (const d of (demandData || [])) {
    demandMap.set(d.warehouse_product_id, Number(d.avg_daily));
  }

  const result = (products || []).map(p => {
    const avgDaily = demandMap.get(p.id) || 0;
    const currentStock = stockMap.get(p.id) || 0;
    const leadTime = p.lead_time_days || 7;
    const safetyDays = p.safety_stock_days || 3;
    const safetyStockQty = Math.ceil(avgDaily * safetyDays);
    const rop = Math.ceil(avgDaily * leadTime) + safetyStockQty;
    const daysOfStock = avgDaily > 0 ? Math.round(currentStock / avgDaily) : 999;

    let status: 'critical' | 'reorder' | 'ok' = 'ok';
    if (currentStock <= safetyStockQty) status = 'critical';
    else if (currentStock <= rop) status = 'reorder';

    return {
      product_id: p.id,
      product_name: p.name,
      category: p.category,
      entity: p.entity,
      unit: p.unit,
      current_stock: currentStock,
      avg_daily: avgDaily,
      lead_time_days: leadTime,
      safety_stock_days: safetyDays,
      safety_stock_qty: safetyStockQty,
      rop,
      days_of_stock: daysOfStock,
      status,
    };
  });

  return result.sort((a, b) => {
    const statusOrder = { critical: 0, reorder: 1, ok: 2 };
    return statusOrder[a.status] - statusOrder[b.status] || a.product_name.localeCompare(b.product_name);
  });
}

export async function updateProductROPConfig(
  productId: number,
  leadTimeDays: number,
  safetyStockDays: number,
) {
  const svc = createServiceSupabase();
  const { data, error } = await svc
    .from('warehouse_products')
    .update({ lead_time_days: leadTimeDays, safety_stock_days: safetyStockDays })
    .eq('id', productId)
    .select()
    .single();
  if (error) throw error;
  return data;
}

// ============================================================
// VENDOR HELPER (re-export for convenience)
// ============================================================

export async function getVendors() {
  const svc = createServiceSupabase();
  const { data, error } = await svc
    .from('warehouse_vendors')
    .select('*')
    .order('name');
  if (error) throw error;
  return data || [];
}
