-- ============================================================================
-- 166: Detailed recurring/fixed costs per workspace
-- ============================================================================
-- Roove's monthly_overhead rows remain untouched. A workspace only switches
-- to detailed fixed costs after it has at least one fixed_cost_item.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.fixed_cost_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_id, name)
);

CREATE TABLE IF NOT EXISTS public.fixed_cost_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.fixed_cost_categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  amount NUMERIC(18, 2) NOT NULL CHECK (amount >= 0),
  quantity NUMERIC(12, 2) NOT NULL DEFAULT 1 CHECK (quantity > 0),
  cost_unit TEXT NOT NULL DEFAULT 'unit',
  recurrence_unit TEXT NOT NULL DEFAULT 'monthly'
    CHECK (recurrence_unit IN ('daily', 'weekly', 'monthly', 'quarterly', 'yearly')),
  recurrence_interval INT NOT NULL DEFAULT 1 CHECK (recurrence_interval > 0),
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE,
  due_day SMALLINT CHECK (due_day BETWEEN 1 AND 31),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_fixed_cost_categories_workspace
  ON public.fixed_cost_categories (workspace_id, is_active, sort_order);

CREATE INDEX IF NOT EXISTS idx_fixed_cost_items_workspace_active
  ON public.fixed_cost_items (workspace_id, is_active, start_date, end_date);

CREATE OR REPLACE FUNCTION public.fixed_cost_monthly_equivalent(
  p_amount NUMERIC,
  p_quantity NUMERIC,
  p_recurrence_unit TEXT,
  p_recurrence_interval INT
)
RETURNS NUMERIC
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT ROUND(
    COALESCE(p_amount, 0)
    * COALESCE(NULLIF(p_quantity, 0), 1)
    * CASE p_recurrence_unit
        WHEN 'daily' THEN 365.0 / 12.0
        WHEN 'weekly' THEN 52.0 / 12.0
        WHEN 'quarterly' THEN 1.0 / 3.0
        WHEN 'yearly' THEN 1.0 / 12.0
        ELSE 1.0
      END
    / GREATEST(COALESCE(p_recurrence_interval, 1), 1),
    2
  );
$$;

CREATE OR REPLACE FUNCTION public.get_workspace_monthly_overhead(
  p_workspace_id UUID,
  p_date_from DATE,
  p_date_to DATE
)
RETURNS TABLE (
  year_month TEXT,
  amount NUMERIC,
  source TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH months AS (
    SELECT month_start::DATE
    FROM generate_series(
      date_trunc('month', p_date_from)::DATE,
      date_trunc('month', p_date_to)::DATE,
      INTERVAL '1 month'
    ) AS series(month_start)
  ),
  authorized AS (
    SELECT (
      public.workspace_can_access(p_workspace_id)
      OR auth.role() = 'service_role'
    ) AS allowed
  ),
  detailed_enabled AS (
    SELECT EXISTS (
      SELECT 1
      FROM public.fixed_cost_items fci
      WHERE fci.workspace_id = p_workspace_id
    ) AS enabled
  ),
  detailed AS (
    SELECT
      to_char(m.month_start, 'YYYY-MM') AS year_month,
      COALESCE(SUM(public.fixed_cost_monthly_equivalent(
        fci.amount,
        fci.quantity,
        fci.recurrence_unit,
        fci.recurrence_interval
      )), 0)::NUMERIC AS amount,
      'detailed'::TEXT AS source
    FROM months m
    CROSS JOIN authorized a
    CROSS JOIN detailed_enabled de
    LEFT JOIN public.fixed_cost_items fci
      ON fci.workspace_id = p_workspace_id
     AND fci.is_active = TRUE
     AND fci.start_date < (m.month_start + INTERVAL '1 month')::DATE
     AND (fci.end_date IS NULL OR fci.end_date >= m.month_start)
    WHERE a.allowed
      AND de.enabled
    GROUP BY m.month_start
  ),
  legacy AS (
    SELECT
      mo.year_month,
      mo.amount::NUMERIC,
      'legacy'::TEXT AS source
    FROM public.monthly_overhead mo
    CROSS JOIN authorized a
    CROSS JOIN detailed_enabled de
    WHERE mo.workspace_id = p_workspace_id
      AND a.allowed
      AND NOT de.enabled
      AND mo.year_month >= to_char(date_trunc('month', p_date_from), 'YYYY-MM')
      AND mo.year_month <= to_char(date_trunc('month', p_date_to), 'YYYY-MM')
  )
  SELECT * FROM detailed
  UNION ALL
  SELECT * FROM legacy;
$$;

REVOKE ALL ON FUNCTION public.get_workspace_monthly_overhead(UUID, DATE, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_workspace_monthly_overhead(UUID, DATE, DATE) TO authenticated, service_role;

ALTER TABLE public.fixed_cost_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fixed_cost_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS fixed_cost_categories_read ON public.fixed_cost_categories;
CREATE POLICY fixed_cost_categories_read ON public.fixed_cost_categories
  FOR SELECT TO authenticated
  USING (public.workspace_can_access(workspace_id));

DROP POLICY IF EXISTS fixed_cost_categories_manage ON public.fixed_cost_categories;
CREATE POLICY fixed_cost_categories_manage ON public.fixed_cost_categories
  FOR ALL TO authenticated
  USING (
    public.workspace_has_role(
      workspace_id,
      ARRAY['workspace_owner', 'admin', 'direktur_finance', 'staf_finance']
    )
  )
  WITH CHECK (
    public.workspace_has_role(
      workspace_id,
      ARRAY['workspace_owner', 'admin', 'direktur_finance', 'staf_finance']
    )
  );

DROP POLICY IF EXISTS fixed_cost_items_read ON public.fixed_cost_items;
CREATE POLICY fixed_cost_items_read ON public.fixed_cost_items
  FOR SELECT TO authenticated
  USING (public.workspace_can_access(workspace_id));

DROP POLICY IF EXISTS fixed_cost_items_manage ON public.fixed_cost_items;
CREATE POLICY fixed_cost_items_manage ON public.fixed_cost_items
  FOR ALL TO authenticated
  USING (
    public.workspace_has_role(
      workspace_id,
      ARRAY['workspace_owner', 'admin', 'direktur_finance', 'staf_finance']
    )
  )
  WITH CHECK (
    public.workspace_has_role(
      workspace_id,
      ARRAY['workspace_owner', 'admin', 'direktur_finance', 'staf_finance']
    )
  );

DROP TRIGGER IF EXISTS set_updated_at_fixed_cost_categories ON public.fixed_cost_categories;
CREATE TRIGGER set_updated_at_fixed_cost_categories
  BEFORE UPDATE ON public.fixed_cost_categories
  FOR EACH ROW EXECUTE FUNCTION public.set_workspace_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_fixed_cost_items ON public.fixed_cost_items;
CREATE TRIGGER set_updated_at_fixed_cost_items
  BEFORE UPDATE ON public.fixed_cost_items
  FOR EACH ROW EXECUTE FUNCTION public.set_workspace_updated_at();

INSERT INTO public.fixed_cost_categories (workspace_id, name, sort_order)
SELECT workspace_id, category_name, sort_order
FROM (
  VALUES
    ('00000000-0000-4000-8000-000000000001'::UUID, 'Payroll & Benefit', 10),
    ('00000000-0000-4000-8000-000000000001'::UUID, 'Sewa & Fasilitas', 20),
    ('00000000-0000-4000-8000-000000000001'::UUID, 'Software & Langganan', 30),
    ('00000000-0000-4000-8000-000000000001'::UUID, 'Operasional Rutin', 40),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'Payroll & Benefit', 10),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'Sewa & Fasilitas', 20),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'Software & Langganan', 30),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'Operasional Rutin', 40)
) AS seed(workspace_id, category_name, sort_order)
ON CONFLICT (workspace_id, name) DO NOTHING;

INSERT INTO public.role_permissions (role, permission_key)
VALUES
  ('admin', 'tab:fixed-costs'),
  ('direktur_finance', 'tab:fixed-costs'),
  ('staf_finance', 'tab:fixed-costs')
ON CONFLICT DO NOTHING;

INSERT INTO public.workspace_role_permissions (
  workspace_id,
  role,
  permission_key
)
SELECT
  workspace_id,
  role,
  'tab:fixed-costs'
FROM (
  VALUES
    ('00000000-0000-4000-8000-000000000001'::UUID, 'admin'),
    ('00000000-0000-4000-8000-000000000001'::UUID, 'direktur_finance'),
    ('00000000-0000-4000-8000-000000000001'::UUID, 'staf_finance'),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'admin'),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'direktur_finance'),
    ('00000000-0000-4000-8000-000000000002'::UUID, 'staf_finance')
) AS seed(workspace_id, role)
ON CONFLICT DO NOTHING;

COMMIT;
