-- Workspace-scoped financial targets for profitability planning.
--
-- A null target_month is the workspace default. A first-of-month date is an
-- immutable monthly override, so changing a future target never rewrites the
-- target used by a completed month.

BEGIN;

CREATE TABLE IF NOT EXISTS public.workspace_financial_targets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  target_month DATE,
  target_operating_profit NUMERIC(18, 2) NOT NULL DEFAULT 0
    CHECK (target_operating_profit >= 0),
  planned_cm3_margin NUMERIC(9, 6) NOT NULL
    CHECK (planned_cm3_margin > 0 AND planned_cm3_margin <= 1),
  target_revenue_override NUMERIC(18, 2)
    CHECK (target_revenue_override IS NULL OR target_revenue_override >= 0),
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (target_month IS NULL OR target_month = date_trunc('month', target_month)::DATE)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_workspace_financial_target_default
  ON public.workspace_financial_targets (workspace_id)
  WHERE target_month IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_workspace_financial_target_month
  ON public.workspace_financial_targets (workspace_id, target_month)
  WHERE target_month IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_workspace_financial_targets_lookup
  ON public.workspace_financial_targets (workspace_id, target_month, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.workspace_financial_target_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  target_id BIGINT,
  action TEXT NOT NULL CHECK (action IN ('insert', 'update', 'delete')),
  before_values JSONB,
  after_values JSONB,
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_workspace_financial_target_audit_workspace
  ON public.workspace_financial_target_audit (workspace_id, changed_at DESC);

DROP TRIGGER IF EXISTS set_updated_at_workspace_financial_targets
  ON public.workspace_financial_targets;
CREATE TRIGGER set_updated_at_workspace_financial_targets
  BEFORE UPDATE ON public.workspace_financial_targets
  FOR EACH ROW EXECUTE FUNCTION public.set_workspace_updated_at();

CREATE OR REPLACE FUNCTION public.audit_workspace_financial_target()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_workspace_id UUID := COALESCE(NEW.workspace_id, OLD.workspace_id);
  v_target_id BIGINT := COALESCE(NEW.id, OLD.id);
  v_changed_by UUID := COALESCE(NEW.updated_by, NEW.created_by, OLD.updated_by, OLD.created_by, auth.uid());
BEGIN
  INSERT INTO public.workspace_financial_target_audit (
    workspace_id,
    target_id,
    action,
    before_values,
    after_values,
    changed_by
  )
  VALUES (
    v_workspace_id,
    v_target_id,
    LOWER(TG_OP),
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) ELSE NULL END,
    v_changed_by
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_audit_workspace_financial_target
  ON public.workspace_financial_targets;
CREATE TRIGGER trg_audit_workspace_financial_target
  AFTER INSERT OR UPDATE OR DELETE ON public.workspace_financial_targets
  FOR EACH ROW EXECUTE FUNCTION public.audit_workspace_financial_target();

ALTER TABLE public.workspace_financial_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_financial_target_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS workspace_financial_targets_read
  ON public.workspace_financial_targets;
CREATE POLICY workspace_financial_targets_read
  ON public.workspace_financial_targets
  FOR SELECT TO authenticated
  USING (public.workspace_can_access(workspace_id));

DROP POLICY IF EXISTS workspace_financial_targets_manage
  ON public.workspace_financial_targets;
CREATE POLICY workspace_financial_targets_manage
  ON public.workspace_financial_targets
  FOR ALL TO authenticated
  USING (
    public.workspace_can_access(workspace_id)
    AND (
      public.is_platform_owner()
      OR EXISTS (
        SELECT 1
        FROM public.workspace_memberships membership
        LEFT JOIN public.workspace_role_permissions permission
          ON permission.workspace_id = membership.workspace_id
         AND permission.role = membership.role
         AND permission.permission_key = 'admin:financial'
        WHERE membership.workspace_id = workspace_financial_targets.workspace_id
          AND membership.user_id = auth.uid()
          AND membership.status = 'active'
          AND (
            membership.role = 'workspace_owner'
            OR permission.permission_key IS NOT NULL
          )
      )
    )
  )
  WITH CHECK (
    public.workspace_can_access(workspace_id)
    AND (
      public.is_platform_owner()
      OR EXISTS (
        SELECT 1
        FROM public.workspace_memberships membership
        LEFT JOIN public.workspace_role_permissions permission
          ON permission.workspace_id = membership.workspace_id
         AND permission.role = membership.role
         AND permission.permission_key = 'admin:financial'
        WHERE membership.workspace_id = workspace_financial_targets.workspace_id
          AND membership.user_id = auth.uid()
          AND membership.status = 'active'
          AND (
            membership.role = 'workspace_owner'
            OR permission.permission_key IS NOT NULL
          )
      )
    )
  );

DROP POLICY IF EXISTS workspace_financial_target_audit_read
  ON public.workspace_financial_target_audit;
CREATE POLICY workspace_financial_target_audit_read
  ON public.workspace_financial_target_audit
  FOR SELECT TO authenticated
  USING (public.workspace_can_access(workspace_id));

GRANT SELECT ON public.workspace_financial_targets TO authenticated;
GRANT ALL ON public.workspace_financial_targets TO service_role;
GRANT SELECT ON public.workspace_financial_target_audit TO authenticated;
GRANT ALL ON public.workspace_financial_target_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.workspace_financial_targets_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.workspace_financial_target_audit_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.audit_workspace_financial_target() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.audit_workspace_financial_target() TO service_role;

COMMENT ON TABLE public.workspace_financial_targets IS
  'Default and monthly profitability targets isolated per workspace.';
COMMENT ON COLUMN public.workspace_financial_targets.target_operating_profit IS
  'Desired profit after monthly overhead, in IDR.';
COMMENT ON COLUMN public.workspace_financial_targets.planned_cm3_margin IS
  'Planned CM3 margin used to derive a stable revenue target; never the volatile actual margin.';
COMMENT ON COLUMN public.workspace_financial_targets.target_revenue_override IS
  'Optional management revenue target that overrides the formula-derived revenue target.';

COMMIT;
